[build]
  command = "npm run-script build"
  publish="weight-lifting-journal-front-end/public"
  base = "weight-lifting-journal-front-end/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200